"""Initial schema creation

Revision ID: d4d7f1fa1fd1
Revises: 
Create Date: 2026-08-09 01:42:45.170190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4d7f1fa1fd1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('service', sa.String(length=50), nullable=False),
    sa.Column('profile_name', sa.String(length=100), nullable=False),
    sa.Column('provider_user_id', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('service', 'profile_name', name='uq_service_profile_name')
    )
    op.create_index(op.f('ix_account_profiles_service'), 'account_profiles', ['service'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('request_json', sa.JSON(), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('source_playlist_id', sa.String(length=255), nullable=True),
    sa.Column('destination_playlist_id', sa.String(length=255), nullable=True),
    sa.Column('source_track_count', sa.Integer(), nullable=True),
    sa.Column('match_checkpoint', sa.Integer(), nullable=False),
    sa.Column('write_checkpoint', sa.Integer(), nullable=False),
    sa.Column('verification_checkpoint', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('lease_holder', sa.String(length=255), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lease_heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_destination_playlist_id'), 'jobs', ['destination_playlist_id'], unique=False)
    op.create_index(op.f('ix_jobs_lease_holder'), 'jobs', ['lease_holder'], unique=False)
    op.create_index(op.f('ix_jobs_source_playlist_id'), 'jobs', ['source_playlist_id'], unique=False)
    op.create_index(op.f('ix_jobs_state'), 'jobs', ['state'], unique=False)
    op.create_table('manual_corrections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_fingerprint', sa.String(length=255), nullable=False),
    sa.Column('spotify_track_id', sa.String(length=255), nullable=True),
    sa.Column('skip_reason', sa.String(length=255), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('origin', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_fingerprint'),
    sa.UniqueConstraint('source_fingerprint', name='uq_manual_corrections_source_fingerprint')
    )
    op.create_index('ix_manual_corrections_source_fingerprint', 'manual_corrections', ['source_fingerprint'], unique=False)
    op.create_table('match_cache',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_fingerprint', sa.String(length=255), nullable=False),
    sa.Column('spotify_track_id', sa.String(length=255), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('origin', sa.String(length=50), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_fingerprint'),
    sa.UniqueConstraint('source_fingerprint', name='uq_match_cache_source_fingerprint')
    )
    op.create_index('ix_match_cache_source_fingerprint', 'match_cache', ['source_fingerprint'], unique=False)
    op.create_table('match_decisions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('source_item_id', sa.String(length=255), nullable=False),
    sa.Column('spotify_track_id', sa.String(length=255), nullable=True),
    sa.Column('score_json', sa.JSON(), nullable=False),
    sa.Column('decision_status', sa.String(length=50), nullable=False),
    sa.Column('reviewed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'source_item_id', name='uq_match_decisions_job_item')
    )
    op.create_index('ix_match_decisions_decision_status', 'match_decisions', ['decision_status'], unique=False)
    op.create_index(op.f('ix_match_decisions_job_id'), 'match_decisions', ['job_id'], unique=False)
    op.create_index('ix_match_decisions_job_item', 'match_decisions', ['job_id', 'source_item_id'], unique=False)
    op.create_table('source_tracks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('source_item_id', sa.String(length=255), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('artist_names', sa.JSON(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.String(length=255), nullable=False),
    sa.Column('channel_title', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'source_item_id', name='uq_source_tracks_job_item')
    )
    op.create_index(op.f('ix_source_tracks_job_id'), 'source_tracks', ['job_id'], unique=False)
    op.create_index('ix_source_tracks_source_item_id', 'source_tracks', ['source_item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_source_tracks_source_item_id', table_name='source_tracks')
    op.drop_index(op.f('ix_source_tracks_job_id'), table_name='source_tracks')
    op.drop_table('source_tracks')
    op.drop_index('ix_match_decisions_job_item', table_name='match_decisions')
    op.drop_index(op.f('ix_match_decisions_job_id'), table_name='match_decisions')
    op.drop_index('ix_match_decisions_decision_status', table_name='match_decisions')
    op.drop_table('match_decisions')
    op.drop_index('ix_match_cache_source_fingerprint', table_name='match_cache')
    op.drop_table('match_cache')
    op.drop_index('ix_manual_corrections_source_fingerprint', table_name='manual_corrections')
    op.drop_table('manual_corrections')
    op.drop_index(op.f('ix_jobs_state'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_source_playlist_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_lease_holder'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_destination_playlist_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_account_profiles_service'), table_name='account_profiles')
    op.drop_table('account_profiles')
    # ### end Alembic commands ###
